services:
  db:
    image: postgres:15
    container_name: smartpod_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: smartpod_django
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/smartpod
    ports:
      - "8000:8000"


volumes:
  postgres_data:
