# Generated by Django 5.1.6 on 2025-03-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255)),
                ('video_name', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('transcription', models.TextField()),
            ],
        ),
    ]
