# Generated by Django 5.1.6 on 2025-02-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('video_name', models.CharField(max_length=255)),
                ('transcription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
