# Generated by Django 5.1.6 on 2025-02-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0002_transcript_delete_audiofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='created_at',
        ),
    ]
