# Generated by Django 5.1.6 on 2025-02-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0003_remove_transcript_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='category',
            new_name='categoryName',
        ),
    ]
