# Generated by Django 5.1.6 on 2025-02-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0004_rename_category_transcript_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
