# Generated by Django 5.1.6 on 2025-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
